config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root to: 'homes#top'
  resources :books, :except => :new
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  # ---- 以下を追加してください ---- #
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  protect_from_forgery :except => [:destroy]
  
  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    # １. データを新規登録するためのインスタンス作成
    @book = Book.new(book_params)
    # ２. データをデータベースに保存するためのsaveメソッド実行
    if @book.save
      flash[:success] = 'Book was successfully created.'
      redirect_to @book
    else
      @books = Book.all
      render :index, status: :unprocessable_entity
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    
    if @book.update(book_params)
      flash[:success] = 'Book was successfully updated.'
      redirect_to @book
    else
      @books = Book.all
      render :edit, status: :unprocessable_entity
    end
  end  
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:success] = 'Book was successfully destroyed.'
    redirect_to books_path, status: :see_other
  end  
  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
<div id="error_explanation">
  <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
  <ul>
  <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>
<% end %>

<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
  <div class="field">
    <label for="book_title">Title</label>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <label for="book_body">Body</label>
    <%= f.text_area :body %>
  </div>
  <%= f.submit 'Update Book' %>
<% end %>

<%= link_to 'Show', book_path(@book), class: 'show_92480' %>|
<a class="back" href="/books">Back</a>

app/views/books/index.html.erb
<p id="notice"><%= flash[:success] %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to 'Show', book_path(book), class: 'show_92480' %> </td>
        <td><%= link_to "Edit", edit_book_path(book), class: 'edit_92480' %></td>
        <td><%= link_to 'Destroy', book_path(book), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?', class: 'destroy_92480' } %></td>
      </tr>
      <% end %>
  </tbody>
</table>


<h2>New book</h2>

<% if @book.errors.any? %>
<div id="error_explanation">
  <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
  <ul>
  <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>
<% end %>

<%= form_with model: @book, url:'/books', local:true do |f| %>
  <div class="field">
    <label for="book_title">Title</label>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <label for="book_body">Body</label>
    <%= f.text_area :body %>
  </div>
  <%= f.submit 'Create Book' %>
<% end %>

<!--<form class="new_book" id="new_book" action="/books" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="ni7ffbc0tbewn4foBV/9Gu5OsC98LXUAH+k/84nYCTajZsMlCm0okZz+LVhWpksc4NJ+9foGH2C0xXskW+Guxw==" />-->

<!--  <div class="field">-->
<!--    <label for="book_title">Title</label>-->
<!--    <input class="book_title" type="text" name="book[title]" id="book_title" />-->
<!--  </div>-->

<!--  <div class="field">-->
<!--    <label for="book_body">Body</label>-->
<!--    <textarea class="book_body" name="book[body]" id="book_body">-->
<!--</textarea>-->
<!--  </div>-->

<!--  <div class="actions">-->
<!--    <input type="submit" name="commit" value="Create Book" data-disable-with="Create Book" />-->
<!--  </div>-->
<!--</form>-->

app/views/books/show.html.erb
<p id="notice"><%= flash[:success] %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @book.body %>
</p>

<%= link_to "Edit", edit_book_path(@book), class: 'edit_92480' %> |
<a class="back" href="/books">Back</a>

app/views/homes/top.html.erb
<h1>ようこそ <strong>Bookers</strong>  へ！</h1>
<p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p><p>印象を共有し交換することができます</p>
<p><a href="/books">start</a></p>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>